/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-01-08 10:12:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.airline.model.*;
import java.text.SimpleDateFormat;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.airline.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("\r\n");
      out.write("    <title>Index Page</title>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Muli:300,400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"ftco-nav\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarTogglerDemo03\" aria-controls=\"navbarTogglerDemo03\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">AIRLINE</a>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo03\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto mt-2 mt-lg-0\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#modalLoginForm\" class=\"nav-link\">Login</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#modalRegisterForm\" class=\"nav-link\">SignUp</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("          \t\t<form method=\"post\" action=\"MainController\">\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"modalLoginForm\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body mx-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"defaultForm-email\" class=\"glyphicon glyphicon-envelope\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tYour email</label> <input type=\"email\" id=\"defaultForm-email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"email\" placeholder=\"Email\" class=\"form-control validate\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"defaultForm-pass\" class=\"glyphicon glyphicon-lock\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tYour password</label> <input type=\"password\" id=\"defaultForm-pass\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"password\" placeholder=\"Password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control validate\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary\" name=\"Login\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Login\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"options text-center text-md-right mt-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNot a member? <a href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-target=\"#modalRegisterForm\" class=\"blue-text\">Sign Up</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tForgot <a href=\"#\" class=\"blue-text\">Password?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-outline-info waves-effect ml-auto\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\" style=\"text-align: center\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          <form method=\"post\" action=\"MainController\">\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"modalRegisterForm\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>Sign Up</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body mx-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"orangeForm-email\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\">Your email</span></label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"email\" name=\"email\" id=\"orangeForm-email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Email\" class=\"form-control validate\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"orangeForm-email\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-earphone\">Your Contact Number</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"contact\" id=\"orangeForm-phone\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"phone number\" class=\"form-control validate\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"orangeForm-pass\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\">Your password</span></label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"password\" id=\"orangeForm-pass\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"password\" class=\"form-control validate\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"orangeForm-name\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\">Re-enter Your password</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"confirmpassword\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"orangeForm-repass\" placeholder=\"re-password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control validate\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"Signup\" value=\"Signup\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-primary\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"options text-center text-md-right mt-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlready Register? <a href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-target=\"#modalLoginForm\" class=\"blue-text\">Sign In</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-outline-info waves-effect ml-auto\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\" style=\"text-align: center\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <section class=\"home-slider owl-carousel\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('images/bg_4.jpg');\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row slider-text align-items-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-7 col-sm-12 ftco-animate\">\r\n");
      out.write("\r\n");
      out.write("              <h1 class=\"mb-3\">Experience the best trip ever through our AIRLINE</h1>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('images/bg_1.jpg');\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row slider-text align-items-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-7 col-sm-12 ftco-animate\">\r\n");
      out.write("\r\n");
      out.write("              <h1 class=\"mb-3\">Making the most out of your holiday</h1>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('images/bg_3.jpg');\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row slider-text align-items-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-7 col-sm-12 ftco-animate\">\r\n");
      out.write("\r\n");
      out.write("              <h1 class=\"mb-3\">Travel Operator Just For You</h1>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- END slider -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"ftco-section-search\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-12 tabulation-search\">\r\n");
      out.write("\r\n");
      out.write("              <p></p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tab-content py-5\" id=\"v-pills-tabContent\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"tab-pane fade show active\" id=\"v-pills-home\" role=\"tabpanel\" aria-labelledby=\"v-pills-home-tab\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"block-17\">\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    ");


                        Date date=new Date();

                        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");

                        String d=sdf.format(date);

					
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                  <form action=\"MainController\" method=\"post\"class=\"d-block d-lg-flex\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"fields d-block d-lg-flex\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"textfield-search one-third\">\r\n");
      out.write("\r\n");
      out.write("                          <div class=\"form-group\"> \r\n");
      out.write("\r\n");
      out.write("                              <label style=\"color:white\" >Source</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" id=\"source\" name=\"source\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										List<Cities> cityList = (List<Cities>) request.getAttribute("citylist");
										for(Cities c:cityList)
										{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=");
      out.print(c.getCityName() );
      out.write('>');
      out.print(c.getAbbreviations() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!--  \t\t<option value=\"KOLKATA\">Kolkata(CCU)</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"JAIPUR\">Jaipur(JAI)</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MUMBAI\">Mumbai(BOM)</option> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"check-in one-third\">\r\n");
      out.write("\r\n");
      out.write("                          <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                              <label style=\"color:white\">Destination</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t <select class=\"form-control\" id=\"destination\" name=\"destination\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									for(Cities c:cityList)
									{
									
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=");
      out.print(c.getCityName() );
      out.write('>');
      out.print(c.getAbbreviations() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"check-out one-third\">\r\n");
      out.write("\r\n");
      out.write("                          <label style=\"color:white\" >Journey Date</label>\r\n");
      out.write("\r\n");
      out.write("                          <input type=\"date\" name=\"date\" id=\"date\" class=\"form-control\" placeholder=");
      out.print(d);
      out.write("></div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"submit\" class=\"search-submit btn btn-primary\" name=\"Flights\" value=\"Flights\">  \r\n");
      out.write("\r\n");
      out.write("                  </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Airline Fellow Tourist</h2>\r\n");
      out.write("\r\n");
      out.write("              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("\r\n");
      out.write("             <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Book Now</h2>\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Flight</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Hotels</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Tour</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Car Rent</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Beach &amp; Resorts</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Mountains</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Cruises</a></li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("\r\n");
      out.write("             <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Top Deals</h2>\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Luxe Hotel</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Venice Tours</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Deluxe Hotels</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Boracay Beach &amp; Resorts</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Beach &amp; Resorts</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Fuente Villa</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Japan Tours</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Philippines Tours</a></li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("\r\n");
      out.write("             <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Contact Information</h2>\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">198 West 21th Street, Suite 721 New York NY 10016</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">+ 1235 2355 98</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">info@yoursite.com</a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">email@email.com</a></li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"ftco-footer-social list-unstyled float-md-right float-lft\">\r\n");
      out.write("\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("\r\n");
      out.write("                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/aos.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/google-map.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
