/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-01-04 08:11:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<!-- BOOTSTRAP STYLES-->\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- FONTAWESOME STYLES-->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- CUSTOM STYLES-->\r\n");
      out.write("<link href=\"css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- Bootstrap CSS CDN -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<!-- GOOGLE FONTS-->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans'\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction checkMe() {\r\n");
      out.write("\t\tif (document.getElementById('ch1').checked == false\r\n");
      out.write("\t\t\t\t&& document.getElementById('ch2').checked == false\r\n");
      out.write("\t\t\t\t&& document.getElementById('ch3').checked == false) {\r\n");
      out.write("\t\t\talert('Please select atleast one criteria for stops');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (document.getElementById('dac').value == ''\r\n");
      out.write("\t\t\t\t|| document.getElementById('aac').value == '') {\r\n");
      out.write("\t\t\talert('Please enter both departure and arrival airport codes');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (document.getElementById('dac').value == document\r\n");
      out.write("\t\t\t\t.getElementById('aac').value) {\r\n");
      out.write("\t\t\talert('Please enter different departure and arrival airport codes');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String emailId=(String)session.getAttribute("user");

      out.write("\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default navbar-cls-top \" role=\"navigation\"\r\n");
      out.write("\t\t\tstyle=\"margin-bottom: 0\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\".sidebar-collapse\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.html\">AirLink</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<p\r\n");
      out.write("\t\t\t\tstyle=\"color: red; padding: 15px 50px 5px 50px; float: right; font-size: 16px;\">\r\n");
      out.write("\t\t\t\tWelcome ");
out.print(emailId); 
      out.write(" &nbsp;</p>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li><a href=\"fontpage.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-home\" style=\"Color: blue\"> HOME</span></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-phone-alt\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"Color: blue\"> CONTACT US</span></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#modalLoginForm\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\" style=\"Color: blue\">\r\n");
      out.write("\t\t\t\t\t\t\tLOG OUT</span></a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!--/.SLIDESHOW END-->\r\n");
      out.write("\t\t<!-- /. NAV TOP  -->\r\n");
      out.write("\t\t<nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"sidebar-collapse\">\r\n");
      out.write("\t\t\t<section id=\"home\" class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"carousel-example\" class=\"carousel slide\"\r\n");
      out.write("\t\t\t\tdata-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"carousel-inner\" style=\"height: 180px\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/aa.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"back-light\"></h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/aa1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-caption \">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"back-light\"></h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/sw1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-caption \">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"back-light\"></h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carousel-example\" data-slide-to=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carousel-example\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carousel-example\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t\t<div id=\"page-inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- /. ROW  -->\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"ActionServlet\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tonsubmit=\"return checkMe();\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"type\" value=\"flightdetails\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Find Flights between two airports</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Enter Departure Airport Code :</h4>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp; <input type=\"text\" name=\"dac\" id=\"dac\" />\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Enter Arrival Airport Code :</h4>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp; <input type=\"text\" name=\"aac\" id=\"aac\" /> <br /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<br /> <input type=\"checkbox\" name=\"stops\" id=\"ch1\" value=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tchecked=\"checked\">Direct Flights (Non-Stop)<br> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"stops\" id=\"ch2\" value=\"1\">Flights\r\n");
      out.write("\t\t\t\t\t\t\twith one stop <br> <input type=\"checkbox\" name=\"stops\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"ch3\" value=\"2\">Flights with two stops <br /> <br />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Show Flights\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-success \">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"AvailSeats.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger square-btn-adjust\">Get Available\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSeats Information</a> <br /> <br /> <a href=\"GetFareInfo.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger square-btn-adjust\">Get Fare\r\n");
      out.write("\t\t\t\t\t\t\t\t\tInformation</a> <br /> <br /> <a href=\"Passenger.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger square-btn-adjust\">Get Passenger List\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor a flight</a> <br /> <br /> <a href=\"viewFlightInstances.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger square-btn-adjust\">Get List of\r\n");
      out.write("\t\t\t\t\t\t\t\t\tflights for a passenger</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Special Deals</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>Fly anywhere in USA starting $99</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>Earn 1000 mileage points for each flight with American\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAirlines</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- /. PAGE INNER  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- /. PAGE WRAPPER  -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/js/canvasjs.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- /. WRAPPER  -->\r\n");
      out.write("\t<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->\r\n");
      out.write("\t<!-- JQUERY SCRIPTS -->\r\n");
      out.write("\t<script src=\"js/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t<!-- BOOTSTRAP SCRIPTS -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- METISMENU SCRIPTS -->\r\n");
      out.write("\t<script src=\"js/jquery.metisMenu.js\"></script>\r\n");
      out.write("\t<!-- CUSTOM SCRIPTS -->\r\n");
      out.write("\t<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
