/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-01-25 09:43:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.airline.model.*;
import java.text.SimpleDateFormat;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.airline.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title>Index Page</title>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Muli:300,400,600,700\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/aos.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flaticon.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function SignUpValidation()\n");
      out.write("{\n");
      out.write("\tvar password = document.getElementById(\"passwordsign\").value;\n");
      out.write("\tvar email = document.getElementById(\"emailsign\").value;\n");
      out.write("\tvar confirmpassword = document.getElementById(\"confirmpasswordsign\").value;\n");
      out.write("\tvar contact = document.getElementById(\"contactsign\").value;\n");
      out.write("\t\n");
      out.write("\tvar status = false;\n");
      out.write("\tvar p=1;\n");
      out.write("\tvar e=1;\n");
      out.write("\tvar cp=1;\n");
      out.write("\tvar c=1;\n");
      out.write("\tvar match=1;\n");
      out.write("\t\n");
      out.write("\tif(email.length == 0)\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Email is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\tp=0;\n");
      out.write("\t}\n");
      out.write("\tif(contact.length == 0 )\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Contact is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\tc=0;\n");
      out.write("\t}\n");
      out.write("\tif(password.length == 0 )\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Password is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse if(password.length < 8)\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Password length must be 8 characters minimum\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\te=0;\n");
      out.write("\t}\n");
      out.write("\tif(confirmpassword.length == 0 )\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Confirm Password is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\tcp=0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tif(confirmpassword == password)\n");
      out.write("\t{\n");
      out.write("\t\tmatch=0;\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Password Mismatch\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tif(e==0 && c==0 && p==0 && cp==0 && match==0)\n");
      out.write("\t{\n");
      out.write("\t\tstatus = true;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\treturn status;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function LoginValidation()\n");
      out.write("{\n");
      out.write("\tvar password = document.getElementById(\"password\").value;\n");
      out.write("\tvar email = document.getElementById(\"email\").value;\n");
      out.write("\tvar status = false;\n");
      out.write("\tvar p=1;\n");
      out.write("\tvar e=1;\n");
      out.write("\tif(email.length == 0)\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Email is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\tp=0;\n");
      out.write("\t}\n");
      out.write("\tif(password.length == 0 )\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Password is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\te=0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tif(p==0 && e==0)\n");
      out.write("\t{\n");
      out.write("\t\tstatus = true;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\treturn status;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function searchValidation()\n");
      out.write("{\n");
      out.write("\t\n");
      out.write("\tvar source = document.getElementById(\"source\").value;\n");
      out.write("\tvar destination = document.getElementById(\"destination\").value;\n");
      out.write("\tvar status = false;\n");
      out.write("\tvar s=1;\n");
      out.write("\tvar d=1;\n");
      out.write("\tif(source == \"Select\")\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Source is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\ts=0;\n");
      out.write("\t}\n");
      out.write("\tif( destination == \"Select\" )\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Destination is Mandatory\");\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\td=0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tif(s==0 && d==0)\n");
      out.write("\t{\n");
      out.write("\t\tstatus = true;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\treturn status;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"ftco-nav\">\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\tdata-target=\"#navbarTogglerDemo03\"\n");
      out.write("\t\t\taria-controls=\"navbarTogglerDemo03\" aria-expanded=\"false\"\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"#\"><h4>AIRLINE</h4></a>\n");
      out.write("\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo03\">\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto mt-2 mt-lg-0 \">\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\"><b>Home</b>\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">(current)</span></a></li>\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"#\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\tdata-target=\"#modalLoginForm\" class=\"nav-link\"><b>Login</b></a></li>\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"#\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\tdata-target=\"#modalRegisterForm\" class=\"nav-link\"><b>SignUp</b></a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\"\n");
      out.write("\t\t\t\t\tplaceholder=\"Search\" aria-label=\"Search\">\n");
      out.write("\t\t\t\t<button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<form method=\"post\" action=\"MainController\" onSubmit=\"return LoginValidation()\">\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modalLoginForm\" tabindex=\"-1\"\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header text-center\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body mx-3\">\n");
      out.write("\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"defaultForm-email\" class=\"glyphicon glyphicon-envelope\">\n");
      out.write("\t\t\t\t\t\t\t\tYour email</label> <input type=\"email\" id=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"email\" placeholder=\"Email\" class=\"form-control validate\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"md-form mb-4\">\n");
      out.write("\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"defaultForm-pass\" class=\"glyphicon glyphicon-lock\">\n");
      out.write("\t\t\t\t\t\t\t\tYour password</label> <input type=\"password\" id=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"password\" placeholder=\"Password\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control validate\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div style=\"text-align: center\">\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary\" name=\"Login\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Login\" style=\"text-align: center\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"options text-center text-md-right mt-1\">\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tNot a member? <a href=\"#\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-target=\"#modalRegisterForm\" class=\"blue-text\">Sign Up</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tForgot <a href=\"#\" class=\"blue-text\">Password?</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-outline-info waves-effect ml-auto\"\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\" style=\"text-align: center\">Close</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<form method=\"post\" action=\"MainController\" onSubmit=\"return SignUpValidation()\">\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modalRegisterForm\" tabindex=\"-1\"\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header text-center\">\n");
      out.write("\t\t\t\t\t\t<h4 style=\"text-align: center\">\n");
      out.write("\t\t\t\t\t\t\t<strong>Sign Up</strong>\n");
      out.write("\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body mx-3\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"orangeForm-email\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\">Your email</span></label> <input\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"email\" name=\"email\" id=\"emailsign\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Email\" class=\"form-control validate\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"orangeForm-email\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-earphone\">Your Contact Number</span></label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"contact\" id=\"contactsign\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"phone number\" class=\"form-control validate\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"orangeForm-pass\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\">Your password   [8 Characters minimum]</span></label> <input\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" name=\"password\" id=\"passwordsign\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"password\" class=\"form-control validate\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\t\t\t\t\t\t\t<label data-error=\"wrong\" data-success=\"right\"\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"orangeForm-name\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\">Re-enter Your password</span></label> <input\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" name=\"confirmpassword\" id=\"confirmpasswordsign\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"re-password\" class=\"form-control validate\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div style=\"text-align: center\">\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" name=\"Signup\" value=\"Signup\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\" style=\"text-align: center\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"options text-center text-md-right mt-1\">\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tAlready Register? <a href=\"#\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-target=\"#modalLoginForm\" class=\"blue-text\">Sign In</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-outline-info waves-effect ml-auto\"\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\" style=\"text-align: center\">Close</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<!-- END nav -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<section class=\"home-slider owl-carousel\">\n");
      out.write("\n");
      out.write("\t<div class=\"slider-item\"\n");
      out.write("\t\tstyle=\"background-image: url('images/bg_4.jpg');\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"overlay\"></div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"row slider-text align-items-center\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-7 col-sm-12 ftco-animate\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h1 class=\"mb-3\">Experience the best trip ever through our\n");
      out.write("\t\t\t\t\t\tAIRLINE</h1>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"slider-item\"\n");
      out.write("\t\tstyle=\"background-image: url('images/bg_1.jpg');\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"overlay\"></div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"row slider-text align-items-center\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-7 col-sm-12 ftco-animate\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h1 class=\"mb-3\">Making the most out of your holiday</h1>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"slider-item\"\n");
      out.write("\t\tstyle=\"background-image: url('images/bg_3.jpg');\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"overlay\"></div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"row slider-text align-items-center\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-7 col-sm-12 ftco-animate\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h1 class=\"mb-3\">Travel Operator Just For You</h1>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<!-- END slider -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"ftco-section-search\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-md-12 tabulation-search\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<p></p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tab-content py-5\" id=\"v-pills-tabContent\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-pane fade show active\" id=\"v-pills-home\"\n");
      out.write("\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"v-pills-home-tab\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-17\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");


                        Date date=new Date();

                        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");

                        String d=sdf.format(date);

					
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"MainController\" method=\"post\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"d-block d-lg-flex\" onSubmit=\"return searchValidation()\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fields d-block d-lg-flex\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"textfield-search one-third\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #ff5f5f\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label style=\"color: white\">Source</label> <select\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"source\" name=\"source\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\" value=\"Select\">Select</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

										List<Cities> cityList = (List<Cities>) request.getAttribute("citylist");
										for(Cities c:cityList)
										{
											String str = c.getCityName()+"("+c.getAbbreviations()+")";
									
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=");
      out.print(c.getCityName() );
      out.write('>');
      out.print(str );
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!--  \t\t<option value=\"KOLKATA\">Kolkata(CCU)</option>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"JAIPUR\">Jaipur(JAI)</option>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MUMBAI\">Mumbai(BOM)</option> -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"check-in one-third\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label style=\"color: white\">Destination</label> <select\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"destination\" name=\"destination\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\" value=\"Select\">Select</option>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

									for(Cities c:cityList)
									{
										String str = c.getCityName()+"("+c.getAbbreviations()+")";

									
									
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=");
      out.print(c.getCityName() );
      out.write('>');
      out.print(str );
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"check-out one-third\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\"color: white\">Journey Date</label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"date\" name=\"date\" id=\"date\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=");
      out.print(d);
      out.write(">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"check-in one-third\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label style=\"color: white\">Passenger</label> <select\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"passenger\" name=\"passenger\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\" value=\"1\" checked>1</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\" value=\"2\">2</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\" value=\"3\">3</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option style=\"background-color: #ff5f5f\" value=\"4\">4</option>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"search-submit btn-primary\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"Flights\" value=\"Flights\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<footer class=\"ftco-footer ftco-bg-dark ftco-section\">\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"row mb-5\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Airline Fellow Tourist</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\tcountries Vokalia and Consonantia, there live the blind texts.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Book Now</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Flight</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Hotels</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Tour</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Car Rent</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Beach &amp; Resorts</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Mountains</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Cruises</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Top Deals</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Luxe Hotel</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Venice Tours</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Deluxe Hotels</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Boracay Beach &amp;\n");
      out.write("\t\t\t\t\t\t\t\tResorts</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Beach &amp; Resorts</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Fuente Villa</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Japan Tours</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">Philippines Tours</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Contact Information</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">198 West 21th\n");
      out.write("\t\t\t\t\t\t\t\tStreet, Suite 721 New York NY 10016</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">+ 1235 2355 98</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">info@yoursite.com</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"py-2 d-block\">email@email.com</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul\n");
      out.write("\t\t\t\t\t\tclass=\"ftco-footer-social list-unstyled float-md-right float-lft\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-twitter\"></span></a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-facebook\"></span></a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-instagram\"></span></a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-12 text-center\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\n");
      out.write("\t\t\t\t\tCopyright &copy;\n");
      out.write("\t\t\t\t\t<script>document.write(new Date().getFullYear());</script>\n");
      out.write("\t\t\t\t\tAll rights reserved\n");
      out.write("\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- loader -->\n");
      out.write("\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\n");
      out.write("\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\n");
      out.write("\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\n");
      out.write("\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\n");
      out.write("\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/popper.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery.stellar.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/aos.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery.animateNumber.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/bootstrap-datepicker.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/jquery.timepicker.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/google-map.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
