/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-01-09 10:26:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.airline.model.*;
import com.airline.controller.*;

public final class ex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.airline.controller");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.airline.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: black\r\n");
      out.write("\t\turl(https://jackrugile.com/images/misc/noise-diagonal.png);\r\n");
      out.write("\tcolor: #444;\r\n");
      out.write("\tfont: 100%/30px 'Helvetica Neue', helvetica, arial, sans-serif;\r\n");
      out.write("\ttext-shadow: 0 1px 0 #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("strong {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("em {\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tbackground: #f5f5f5;\r\n");
      out.write("\tborder-collapse: separate;\r\n");
      out.write("\tbox-shadow: inset 0 1px 0 #fff;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 24px;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tbackground: url(https://jackrugile.com/images/misc/noise-diagonal.png),\r\n");
      out.write("\t\tlinear-gradient(#777, #444);\r\n");
      out.write("\tborder-left: 1px solid #555;\r\n");
      out.write("\tborder-right: 1px solid #777;\r\n");
      out.write("\tborder-top: 1px solid #555;\r\n");
      out.write("\tborder-bottom: 1px solid #333;\r\n");
      out.write("\tbox-shadow: inset 0 1px 0 #999;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tpadding: 10px 15px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttext-shadow: 0 1px 0 #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:after {\r\n");
      out.write("\tbackground: linear-gradient(rgba(255, 255, 255, 0),\r\n");
      out.write("\t\trgba(255, 255, 255, .08));\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 25%;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tmargin: 1px 0 0 0;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 25%;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:first-child {\r\n");
      out.write("\tborder-left: 1px solid #777;\r\n");
      out.write("\tbox-shadow: inset 1px 1px 0 #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:last-child {\r\n");
      out.write("\tbox-shadow: inset -1px 1px 0 #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tborder-right: 1px solid #fff;\r\n");
      out.write("\tborder-left: 1px solid #e8e8e8;\r\n");
      out.write("\tborder-top: 1px solid #fff;\r\n");
      out.write("\tborder-bottom: 1px solid #e8e8e8;\r\n");
      out.write("\tpadding: 10px 15px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttransition: all 300ms;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td:first-child {\r\n");
      out.write("\tbox-shadow: inset 1px 0 0 #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td:last-child {\r\n");
      out.write("\tborder-right: 1px solid #e8e8e8;\r\n");
      out.write("\tbox-shadow: inset -1px 0 0 #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr {\r\n");
      out.write("\tbackground: url(https://jackrugile.com/images/misc/noise-diagonal.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(odd) td {\r\n");
      out.write("\tbackground: #f1f1f1\r\n");
      out.write("\t\turl(https://jackrugile.com/images/misc/noise-diagonal.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:last-of-type td {\r\n");
      out.write("\tbox-shadow: inset 0 -1px 0 #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:last-of-type td:first-child {\r\n");
      out.write("\tbox-shadow: inset 1px -1px 0 #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:last-of-type td:last-child {\r\n");
      out.write("\tbox-shadow: inset -1px -1px 0 #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody:hover td {\r\n");
      out.write("\tcolor: transparent;\r\n");
      out.write("\ttext-shadow: 0 0 3px #aaa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody:hover tr:hover td {\r\n");
      out.write("\tcolor: #444;\r\n");
      out.write("\ttext-shadow: 0 1px 0 #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		User user = (User) session.getAttribute("user");

		if (user != null)

		{
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h2>");
      out.print(user.getEmailId());
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\r\n");
      out.write("\t\t<h1 style=\"color: white\">Flight List</h1>\r\n");
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t<table>\r\n");
      out.write("\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Flight Id</th>\r\n");
      out.write("\t\t\t\t<th>Airline Name</th>\r\n");
      out.write("\t\t\t\t<th>Departure</th>\r\n");
      out.write("\t\t\t\t<th>Arrival</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<th>Date</th>\r\n");
      out.write("\t\t\t\t<th>Departure Time</th>\r\n");
      out.write("\t\t\t\t<th>Arrival Time</th>\r\n");
      out.write("\t\t\t\t<th>Duration</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<th>Business Seat</th>\r\n");
      out.write("\t\t\t\t<th>Business Seat Price</th>\r\n");
      out.write("\t\t\t\t<th>Economy Seat</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<th>Economy Seat Price</th>\r\n");
      out.write("\t\t\t\t<th>Booking Status</th>\r\n");
      out.write("\t\t\t\t<th>ReserveSeat</th>\r\n");
      out.write("\t\t\t\t<th>PrebookSeat</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				List<Flight> flightlist = (List<Flight>) session.getAttribute("flights");

				for (Flight f : flightlist) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getFlightId());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getAirlineName());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getSource());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getDestination());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getDate());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getDepartureTime());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getArrivalTime());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getDuration());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getBusinessSeat());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getBusinessPrice());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getEconomySeat());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(f.getEconomyPrice());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"FlightDetailsController\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-color: #32CD32;\" name=\"button\" value=booknow>BOOK\r\n");
      out.write("\t\t\t\t\t\tNOW</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-color: #32CD32;\" name=\"button\" value=reserve>Reserve\r\n");
      out.write("\t\t\t\t\t\tNow</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-color: #32CD32;\" name=\"button\" value=\"prebook\">Prebook\r\n");
      out.write("\t\t\t\t\t\tNow</button>\r\n");
      out.write("\t\t\t\t</td> <input type=\"hidden\" name=\"flightid\" value=");
      out.print(f.getFlightId());
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"airlinename\"\r\n");
      out.write("\t\t\t\t\tvalue=");
      out.print(f.getAirlineName());
      out.write("> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\tname=\"source\" value=");
      out.print(f.getSource());
      out.write("> <input\r\n");
      out.write("\t\t\t\t\ttype=\"hidden\" name=\"destination\" value=");
      out.print(f.getDestination());
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"date\" value=");
      out.print(f.getDate());
      out.write("> <input\r\n");
      out.write("\t\t\t\t\ttype=\"hidden\" name=\"departuretime\" value=");
      out.print(f.getDepartureTime());
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"arrivaltime\"\r\n");
      out.write("\t\t\t\t\tvalue=");
      out.print(f.getArrivalTime());
      out.write("> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\tname=\"duration\" value=");
      out.print(f.getDuration());
      out.write("> <input\r\n");
      out.write("\t\t\t\t\ttype=\"hidden\" name=\"businessseat\" value=");
      out.print(f.getBusinessSeat());
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"businessprice\"\r\n");
      out.write("\t\t\t\t\tvalue=");
      out.print(f.getBusinessPrice());
      out.write("> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\tname=\"economyseat\" value=");
      out.print(f.getEconomySeat());
      out.write("> <input\r\n");
      out.write("\t\t\t\t\ttype=\"hidden\" name=\"economyprice\" value=");
      out.print(f.getEconomyPrice());
      out.write(">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
